_target_: pytorch_lightning.Trainer

devices: 1

min_epochs: 1
max_epochs: 150

log_every_n_steps: 50

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
