_target_: ai4eo_mapyourcity.models.mapyourcity_model.MapYourCityModel
learning_rate: 0.00001
weight_decay: 0.005
num_classes: 7
weighted_loss: True
class_weights:
  '0' : 0.0647
  '1' : 0.158
  '2' : 0.160
  '3' : 0.140
  '4' : 0.116
  '5' : 0.143
  '6' : 0.219
validation_metric: confusion_matrix
loss_id: cross_entropy
backbone: null
