_target_: ai4eo_mapyourcity.models.mapyourcity_model.MapYourCityModel
learning_rate: 0.00001
num_classes: 7
model: swin_tiny_patch4_window7_224.ms_in1k
pretrained: True
weighted_loss: True
class_weights:
  '0' : 0.0647
  '1' : 0.158
  '2' : 0.160
  '3' : 0.140
  '4' : 0.116
  '5' : 0.143
  '6' : 0.219
