defaults:
  - mapyourcity_model.yaml

backbone:
  _target_: ai4eo_mapyourcity.models.backbones.SimpleConvNet
  num_classes: ${model.num_classes}
  model_id: simpleconvnet # required for compatibility
  in_channels: 15
  out_channels: 36
  kernel_size: 5
  pool_size: 2
  mid_units: 512
  dropout: 0.1
