defaults:
  - mapyourcity_model.yaml

backbone:
  _target_: ai4eo_mapyourcity.models.backbones.SimpleConvNet
  in_channels: 12
  mid_channels: 36
  kernel_size: 5
  mid_units: 512
  out_units: 128
  dropout: 0.1
