defaults:
  - mapyourcity_model.yaml

backbone:
  _target_: ai4eo_mapyourcity.models.backbones.TIMMCollection
  model_id: swinv2_tiny_window16_256.ms_in1k
  is_pretrained: True
  num_classes: ${model.num_classes}
