defaults:
  - mapyourcity_model.yaml

backbone:
  _target_: ai4eo_mapyourcity.models.backbones.TIMMCollectionCombined
  model_id: 
    topview: null 
    streetview: null
    sentinel2: null
  is_pretrained: True
  num_classes: ${model.num_classes}
  out_features:
    topview: 768
    streetview: 768
    sentinel2: 768
  fusion_mode: max
