defaults:
  - mapyourcity_model.yaml

backbone:
  _target_: ai4eo_mapyourcity.models.backbones.TIMMCollectionCombined
  model_id: swinv2_tiny_window16_256.ms_in1k
  is_pretrained: True
  num_classes: ${model.num_classes}
  num_models: 3 # How many models to combine
  out_features: 768 # from pretrained model
  mid_features: 512
