# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: combined.yaml # choose the datamodule for evaluation
  - model: timm_combined.yaml
  - callbacks: null
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}/..

# matches train.yaml
data_dir: ${original_work_dir}/data/AI4EO-MapYourCity/v1/building-age-dataset/
fold: 0
fold_dir: ${original_work_dir}/data/AI4EO-MapYourCity/splits/

print_config: True

ignore_warnings: True

seed: null

name: "default"

trainer:
  devices: 1

# passing checkpoint path is necessary
ckpt_path: logs/experiments/runs/default/2022-03-21_04-40-51/checkpoints/last.ckpt
