_target_: ai4eo_mapyourcity.datamodules.mapyourcity_datamodule.MapYourCityCombinedDataModule

defaults:
  - mapyourcity.yaml

batch_size: 32

dataset_options:
  transform: default
  model_id: ${model.backbone.model_id}
  dataset_options_topview:
    transform: default
    img_file: orthophoto.tif
  dataset_options_streetview:
    transform: default
    img_file: street.jpg
  dataset_options_sentinel2:
    transform: patch
    img_file: s2_l2a.tif
