_target_: ai4eo_mapyourcity.datamodules.mapyourcity_datamodule.MapYourCityDataModule

batch_size: 64 # largest is 256
num_workers: 8
pin_memory: False

dataset_options:
  data_dir: ${data_dir} # data_dir is specified in train.yaml
  fold: ${fold} # is specified in train.yaml
  fold_dir: ${fold_dir}
  model_id: ${model.backbone.model_id}
