_target_: ai4eo_mapyourcity.datamodules.mapyourcity_datamodule.MapYourCityDataModule

data_dir: ${data_dir} # data_dir is specified in train.yaml
batch_size: 64 # largest is 256
num_workers: 8
pin_memory: False
fold: ${fold} # is specified in train.yaml
fold_dir: ${fold_dir}
img_type: topview
transform: center_crop
target_size: 224
sentinel2_mode: rgb
