_target_: ai4eo_mapyourcity.datamodules.mapyourcity_datamodule.MapYourCityDataModule

defaults:
  - mapyourcity.yaml

dataset_options:
  img_file: s2_l2a.tif
  transform: default
  use_ndvi: True
  use_ndbi: True
  use_ndwi: True
  in_channels: 15 # calculate here
  input_size: 64
