_target_: ai4eo_mapyourcity.datamodules.mapyourcity_datamodule.MapYourCityDataModule

defaults:
  - mapyourcity.yaml

dataset_options:
  img_file: s2_l2a.tif
  transform: default
  bands: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B08A', 'B09', 'B10', 'B11', 'B12']
  use_ndvi: True
  use_ndbi: True
  use_ndwi: True
