# @package _global_

# overfits to 3 batches

defaults:
  - default.yaml

trainer:
  max_epochs: 20
  overfit_batches: 3
  log_every_n_steps: 1

callbacks:
  early_stopping:
    patience: ${trainer.max_epochs}
